CREATE TABLE IF NOT EXISTS USUARIO (
	id SERIAL PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	senha VARCHAR(255) NOT NULL,
	criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TURMA (
	id SERIAL PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
    alunos text,
	criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS UC (
	id SERIAL PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
    link_diario text,
	criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
